//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modeln
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Targeta = new HashSet<Targeta>();
        }

        public string id { get; set; }
        public string NombreEmpresa { get; set; }
        public string Tipo_empresa { get; set; }
        public string Tamaño_empresa { get; set; }
        public string ContactoComercial { get; set; }
        public string ContactoGerencial { get; set; }
        public string ContactoAdmin { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Targeta> Targeta { get; set; }
        

    }
}
