//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modeln
{
    using System;
    using System.Collections.Generic;

    public partial class Targeta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Targeta()
        {
            this.Clientes = new HashSet<Cliente>();
        }

        public int id { get; set; }
        public string No__targeta { get; set; }
        public string NombreTrgeta { get; set; }
        public System.TimeSpan FechaExp { get; set; }
        public string tipoTarg { get; set; }
        public string Cvv { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente> Clientes { get; set; }
        

    }
}
